import { alertMessages, dashboard, events, faqs, notices, products, quickMenus, roaServices, safezoneFacilities } from './mockData';

const navItems = [
  ['상품', 'products'], ['행사', 'events'], ['서비스', 'services'], ['세이프존', 'safezone'],
  ['ROA 제휴', 'roa'], ['채용', 'hiring'], ['창업/가맹', 'franchise'], ['고객센터', 'cs'],
] as const;

const sectionClass = 'mx-auto max-w-7xl px-4 py-10';
const cardClass = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm';

export default function App() {
  return <div className="min-h-screen bg-slate-50 text-brand-navy"><Header /><AlertBar /><main><Hero /><QuickMenu /><StatusDashboard /><ProductSection /><EventSection /><SafezoneSection /><AnomalySection /><AdultRestrictedSafetySection /><ROAPartnershipSection /><HiringSection /><ManagerComment /><NoticeSection /><FAQSection /><FranchiseSection /></main><Footer /></div>;
}

function Header() { return <header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto max-w-7xl px-4 py-2 text-sm flex justify-end gap-4">{['로그인', '365 앱', '고객센터', '점포 제보', '채용'].map((i)=><button key={i}>{i}</button>)}</div><div className="mx-auto max-w-7xl px-4 py-4 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><h1 className="text-3xl font-black text-amber-500">365 STORE</h1><nav className="flex flex-wrap gap-3 text-sm font-semibold">{navItems.map(([label,id])=><a key={id} href={`#${id}`} className="rounded-full px-3 py-2 hover:bg-amber-50">{label}</a>)}</nav><span className="rounded-full bg-amber-100 px-4 py-2 text-xs font-bold">일온시 포탈 경보: 관심 (1단계)</span></div></header>; }
function AlertBar(){return <div className="bg-brand-navy text-white text-sm"><div className="mx-auto max-w-7xl px-4 py-2 flex flex-wrap gap-4">{alertMessages.map((m)=><p key={m}>• {m}</p>)}</div></div>}
function Hero(){const banners=[['오늘의 식사부터 내일의 안전까지','365 STORE 일온시 지점은 평상시에는 편의점, 비상시에는 생활 안전 거점입니다.'],['포탈 경보에도 열려 있는 가장 가까운 세이프존','대피 공간, 비상용품, ROA 직통 신고 시스템을 갖춘 대형 세이프존형 매장입니다.'],['레인저와 시민을 위한 24시간 보급 거점','ROA 앱 인증 고객은 호출기 배터리 교환, 출동 전 픽업, 오염 의류 밀봉 서비스를 이용할 수 있습니다.']];return <section className={sectionClass}>{<div className="grid gap-4 md:grid-cols-3">{banners.map(([t,d])=><article key={t} className="rounded-2xl bg-gradient-to-br from-amber-100 to-white p-6 border"><h2 className="text-xl font-bold">{t}</h2><p className="mt-2 text-sm">{d}</p></article>)}</div>}</section>}
function QuickMenu(){return <section id="services" className={sectionClass}><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{quickMenus.map((m)=><button key={m} className={`${cardClass} text-left font-semibold`}>⚡ {m}</button>)}</div></section>}
function StatusDashboard(){return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">매장 운영 대시보드</h3><div className="grid gap-3 md:grid-cols-4">{dashboard.map(([k,v])=><div key={k} className={cardClass}><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-bold">{v}</p></div>)}</div></section>}
function ProductSection(){return <section id="products" className={sectionClass}><h3 className="text-2xl font-bold mb-4">상품</h3><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{products.map((p)=><article key={p.name} className={cardClass}><div className="flex justify-between"><span className="text-xs bg-amber-100 px-2 py-1 rounded">{p.category}</span><span className="text-xs">일온시 지점 취급</span></div><h4 className="mt-2 font-bold">{p.name}</h4><p className="text-sm mt-1">{p.description}</p><p className="mt-2 text-sm">가격 {p.price} · 재고 {p.stock}</p></article>)}</div></section>}
function EventSection(){return <section id="events" className={sectionClass}><h3 className="text-2xl font-bold mb-4">행사/이벤트</h3><div className="grid gap-3 md:grid-cols-2">{events.map((e)=><article key={e.title} className={cardClass}><h4 className="font-bold">{e.title}</h4><p className="text-xs text-slate-500">{e.period}</p><p className="text-sm mt-2">{e.detail}</p>{e.note && <p className="mt-3 text-xs italic">{e.note}</p>}</article>)}</div></section>}
function SafezoneSection(){return <section id="safezone" className={sectionClass}><h3 className="text-2xl font-bold mb-4">세이프존 안내</h3><div className="grid gap-4 md:grid-cols-2"><div className={cardClass}><p>관심 단계: 일반 영업</p><p>주의 단계: 대피 동선 안내</p><p>경계 단계: 동측 구역 세이프존 전환</p><p>심각 단계: 방호 셔터 하강, ROA 직통 신고</p></div><div className={`${cardClass} grid grid-cols-1 gap-2`}>{safezoneFacilities.map((f)=><p key={f}>• {f}</p>)}</div></div></section>}
function AnomalySection(){const items=['공간 왜곡','감각 교란','의태 외계체','접촉성 오염','시간 지연'];return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">일온시 이상현상 생활안전 안내</h3><p className="mb-4 text-sm">위험 등급 1~2 생활형 이상현상 신고·임시 격리를 지원하며, 3등급 이상은 ROA 및 이능력자 관리국으로 즉시 이관됩니다.</p><div className="grid gap-3 md:grid-cols-5">{items.map((i)=><div className={cardClass} key={i}>{i}</div>)}</div></section>}
function AdultRestrictedSafetySection(){return <section className={sectionClass}><h3 className="text-2xl font-bold mb-3">성인 제한 특수 재난 안내</h3><div className={cardClass}><p>일부 포탈 유래 재난은 성인 생체 신호 기반 특수 재난으로 분류됩니다.</p><p>활성 구역은 민간인 출입이 제한되며 미성년자는 법적으로 출입할 수 없습니다.</p><p>상세 대응은 ROA 및 이능력자 관리국 지침을 따릅니다.</p></div></section>}
function ROAPartnershipSection(){return <section id="roa" className={sectionClass}><h3 className="text-2xl font-bold mb-4">ROA 제휴 서비스</h3><div className="grid gap-3 md:grid-cols-3">{roaServices.map((s)=><article key={s} className={cardClass}><h4 className="font-semibold">{s}</h4><p className="text-sm mt-2">{s.includes('픽업')?'출동 전 3분 픽업':s.includes('배터리')?'호출기 배터리 20분 급속 충전':'임무 복귀자 고열량 식사 패키지'}</p></article>)}</div></section>}
function HiringSection(){return <section id="hiring" className={sectionClass}><h3 className="text-2xl font-bold mb-4">외인혼혈 세이프존 보조 스태프 3개월 기간제 시범 고용</h3><div className="grid gap-4 md:grid-cols-2"><article className={cardClass}><p>차별 금지 원칙을 준수하며, 위험 대응 적응력을 갖춘 지원자를 우대합니다.</p><ul className="mt-2 text-sm list-disc pl-5"><li>세이프존 일일 점검</li><li>비상용품 입출고 관리</li><li>경보 발령 시 대피 안내 보조</li><li>야간 안전 점검</li></ul></article><article className={cardClass}><ul className="text-sm list-disc pl-5"><li>계약 기간 3개월</li><li>성인 지원자만 가능</li><li>야간 근무 가능자 우대</li><li>ROA 또는 이능력자 관리국 등록 정보 확인 절차</li></ul></article></div></section>}
function ManagerComment(){const comments=['재난은 막을 수 없어도, 재난 동선은 설계할 수 있습니다.','대피 공간은 무료입니다. 소모품은 합리적인 가격으로 준비했습니다.','일온시의 위험은 곧 준비된 매장의 기회입니다.','안전도 결국 재고와 동선에서 시작됩니다.']; return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">점장 코멘트</h3><div className="grid md:grid-cols-2 gap-3">{comments.map((c)=><blockquote key={c} className={`${cardClass} border-l-4 border-amber-400`}>{c}</blockquote>)}</div></section>}
function NoticeSection(){return <section id="cs" className={sectionClass}><h3 className="text-2xl font-bold mb-4">고객센터/공지사항</h3><ul className={cardClass}>{notices.map((n)=><li className="py-2 border-b last:border-0" key={n}>{n}</li>)}</ul></section>}
function FAQSection(){return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">FAQ</h3><div className="space-y-3">{faqs.map(([q,a])=><article key={q} className={cardClass}><p className="font-semibold">Q. {q}</p><p className="mt-2 text-sm">A. {a}</p></article>)}</div></section>}
function FranchiseSection(){return <section id="franchise" className={sectionClass}><h3 className="text-2xl font-bold mb-4">창업/가맹 안내</h3><div className="grid gap-3 md:grid-cols-4">{['365 STORE 일반형','365 STORE 세이프존형','365 STORE ROA 협력형','365 STORE 포탈 위험권역 특수형'].map((m)=><div key={m} className={cardClass}>{m}</div>)}</div><p className="mt-4">“입지는 위험이 아니라 수요입니다.” · “365 STORE는 포탈 시대의 생활 인프라를 설계합니다.”</p></section>}
function Footer(){return <footer className="bg-brand-navy text-white mt-8"><div className="mx-auto max-w-7xl px-4 py-8 text-sm"><p className="font-bold">365 STORE 일온시 지점</p><p>일온시 중앙순환로 365, 일온세이프타워 1층 · 고객센터 1588-0365 · 24시간 운영</p><p className="mt-2">본 사이트의 브랜드·기관·지역은 가상 설정이며 실제와 무관합니다. 미성년자 보호 규정, 이상현상 신고 안내, ROA/이능력자 관리국 관련 내용은 세계관 설정입니다.</p></div></footer>}
