import { useMemo, useState } from 'react';
import { alertMessages, dashboard, events, faqs, hiringData, noticeDetails, notices, products, roaServiceDetails, roaServices, safezoneFacilities, safezoneOverview, safezoneSteps } from './mockData';

type Page = 'home' | 'customer' | 'login' | 'signup' | 'hiringDetail';
type User = { id: string; password: string };

const navItems: { label: string; id?: string; page?: Page }[] = [{ label: '상품', id: 'products' }, { label: '행사', id: 'events' }, { label: '세이프존', id: 'safezone' }, { label: 'ROA 제휴', id: 'roa' }, { label: '고객센터', page: 'customer' }];
const sectionClass = 'mx-auto max-w-7xl px-4 py-10';
const cardClass = 'rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';

export default function App() {
  const [page, setPage] = useState<Page>('home');
  const [signedUser, setSignedUser] = useState<User | null>(null);
  const [loggedInUser, setLoggedInUser] = useState<string | null>(null);
  const [selectedProduct, setSelectedProduct] = useState<string | null>(null);
  const isLoggedIn = useMemo(() => !!loggedInUser, [loggedInUser]);

  return <div className="min-h-screen bg-slate-50 text-brand-navy"><Header user={loggedInUser} onGoLogin={() => setPage('login')} onGoSignup={() => setPage('signup')} onGoCustomer={() => setPage('customer')} onGoHome={() => setPage('home')} />{page === 'home' && <AlertBar />}<main>{page === 'home' && <HomePage onBuyProduct={setSelectedProduct} showDiscount={isLoggedIn} onOpenHiring={() => setPage('hiringDetail')} />}{page === 'customer' && <CustomerCenterPage onGoHome={() => setPage('home')} />}{page === 'login' && <LoginPage signedUser={signedUser} onLogin={(id) => { setLoggedInUser(id); setPage('home'); }} />}{page === 'signup' && <SignUpPage onSigned={(user) => { setSignedUser(user); setPage('login'); }} />}{page === 'hiringDetail' && <HiringGuidePage onGoHome={() => setPage('home')} />}</main>{selectedProduct && <ProductDetailModal productName={selectedProduct} isMember={isLoggedIn} onClose={() => setSelectedProduct(null)} />}<Footer /></div>;
}

function Header({ user, onGoLogin, onGoSignup, onGoCustomer, onGoHome }: { user: string | null; onGoLogin: () => void; onGoSignup: () => void; onGoCustomer: () => void; onGoHome: () => void }) { return <header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto max-w-7xl px-4 py-2 text-sm flex justify-end gap-4"><button onClick={onGoLogin}>{user ? `${user}님` : '로그인'}</button><button onClick={onGoSignup}>회원가입</button><button onClick={onGoCustomer}>고객센터</button></div><div className="mx-auto max-w-7xl px-4 py-4 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><button onClick={onGoHome} className="text-3xl font-black text-amber-500 text-left">365 STORE</button><nav className="flex flex-wrap gap-3 text-sm font-semibold">{navItems.map((item) => item.page ? <button key={item.label} onClick={onGoCustomer} className="rounded-full px-3 py-2 hover:bg-amber-50">{item.label}</button> : <a key={item.id} href={`#${item.id}`} className="rounded-full px-3 py-2 hover:bg-amber-50">{item.label}</a>)}</nav><span className="rounded-full bg-amber-100 px-4 py-2 text-xs font-bold">일온시 포탈 경보: 관심 (1단계)</span></div></header>; }
function HomePage({ onBuyProduct, showDiscount, onOpenHiring }: { onBuyProduct: (name: string) => void; showDiscount: boolean; onOpenHiring: () => void }) { return <><Hero />{showDiscount && <DiscountTab />}<StatusDashboard /><ProductSection onBuy={onBuyProduct} /><EventSection /><SafezoneSection /><ROAPartnershipSection /><HiringSection onOpenHiring={onOpenHiring} /><NoticeSection /></>; }
function AlertBar() { return <div className="bg-brand-navy text-white text-sm"><div className="mx-auto max-w-7xl px-4 py-2 flex flex-wrap gap-4">{alertMessages.map((m) => <p key={m}>• {m}</p>)}</div></div>; }
function Hero() { return <section className={sectionClass}><div className="grid gap-4 md:grid-cols-3">{[['오늘의 식사부터 내일의 안전까지', '평상시에는 편의점, 비상시에는 생활 안전 거점.'], ['포탈 경보에도 열려 있는 세이프존', '대피 공간과 비상용품, ROA 직통 신고 체계 운영.'], ['레인저와 시민을 위한 24시간 보급', '호출기 배터리 교환·출동 전 픽업·밀봉 서비스 지원.']].map(([t, d]) => <article key={t} className="rounded-2xl bg-gradient-to-br from-amber-100 to-white p-6 border"><h2 className="text-xl font-bold">{t}</h2><p className="mt-2 text-sm">{d}</p></article>)}</div></section>; }
function DiscountTab() { return <section className={sectionClass}><div className="rounded-xl bg-emerald-50 border border-emerald-200 p-4"><h3 className="font-bold text-emerald-700">고객 할인 메뉴</h3><p className="text-sm mt-1">회원 구매 시 즉시 할인 + 구매 적립이 적용됩니다.</p></div></section>; }
function StatusDashboard() { return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">매장 현황</h3><p className="text-sm text-slate-600 mb-3">위험 등급은 1~5단계로 분류됩니다. 현재 매장 운영 기준은 1단계(관심)입니다.</p><div className="grid gap-3 md:grid-cols-3">{dashboard.map(([k, v]) => <div key={k} className={cardClass}><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-bold">{v}</p></div>)}</div></section>; }
function ProductSection({ onBuy }: { onBuy: (name: string) => void }) { return <section id="products" className={sectionClass}><h3 className="text-2xl font-bold mb-4">상품</h3><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{products.map((p) => <article key={p.name} className={cardClass}><div className="flex justify-between"><span className="text-xs bg-amber-100 px-2 py-1 rounded">{p.category}</span><span className="text-xs rounded-full bg-slate-100 px-2 py-1">{p.stock}</span></div><h4 className="mt-2 font-bold">{p.name}</h4><p className="text-sm mt-1">{p.description}</p><p className="mt-2 text-sm">가격 {p.price}</p><button onClick={() => onBuy(p.name)} className="mt-3 rounded bg-brand-navy text-white px-3 py-2 text-sm">구매하기</button></article>)}</div></section>; }
function ProductDetailModal({ productName, isMember, onClose }: { productName: string; isMember: boolean; onClose: () => void }) { const [qty, setQty] = useState(1); const [popup, setPopup] = useState(''); const product = products.find((p) => p.name === productName); if (!product) return null; const price = Number(product.price.replace(/[₩,]/g, '')); const discount = isMember ? Math.floor(price * 0.05) : 0; const final = (price - discount) * qty; const payType = isMember ? '회원 구매(할인·적립 적용)' : '비회원 구매(정가 적용)'; const doAction = (action: string) => setPopup(`${action} 완료: ${product.name} / ${payType}`); return <div className="fixed inset-0 z-50 bg-slate-900/50"><div className="absolute right-0 top-0 h-full w-full max-w-md bg-white p-6 shadow-2xl overflow-y-auto"><div className="flex justify-between items-start"><h3 className="text-xl font-bold">상품 상세 구매</h3><button onClick={onClose}>닫기</button></div><h4 className="mt-4 text-lg font-bold">{product.name}</h4><div className="mt-2 flex gap-2"><span className="text-xs rounded-full bg-amber-100 px-2 py-1">{product.category}</span><span className="text-xs rounded-full bg-slate-100 px-2 py-1">재고 {product.stock}</span></div><p className="mt-3 text-sm">{product.description}</p><p className="mt-2 text-sm"><b>구매 유형:</b> {payType}</p><p className="mt-2 font-semibold">단가 {product.price} {isMember && <span className="text-emerald-700">(회원할인 -₩{discount.toLocaleString()})</span>}</p><p className="mt-1 font-bold text-lg">결제 예상가 ₩{final.toLocaleString()}</p><p className="mt-3 text-sm"><b>추천 이용 상황</b><br />{product.usageTip}</p><p className="mt-3 text-sm"><b>관련 상품 추천</b><br />{product.related.join(', ')}</p><ul className="mt-3 text-sm list-disc pl-5"><b>주의사항</b>{product.cautions.map((c) => <li key={c}>{c}</li>)}</ul><div className="mt-4"><label className="text-sm font-semibold">수량 선택</label><input type="number" min={1} value={qty} onChange={(e) => setQty(Number(e.target.value))} className="mt-1 w-24 border rounded p-2" /></div><div className="mt-5 flex gap-2"><button onClick={() => doAction('상품 구매')} className="rounded bg-amber-500 px-4 py-2 text-white">상품 구매</button><button onClick={() => doAction('장바구니 담기')} className="rounded bg-brand-navy px-4 py-2 text-white">장바구니 담기</button></div>{popup && <div className="mt-4 rounded-lg border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800">{popup}</div>}</div></div>; }
function EventSection() { return <section id="events" className={sectionClass}><h3 className="text-2xl font-bold mb-4">행사/이벤트</h3><div className="grid gap-3 md:grid-cols-2">{events.map((e) => <article key={e.title} className={cardClass}><h4 className="font-bold">{e.title}</h4><p className="text-xs text-slate-500">{e.period}</p><p className="text-sm mt-2">{e.detail}</p></article>)}</div></section>; }
function SafezoneSection() { return <section id="safezone" className={sectionClass}><h3 className="text-2xl font-bold mb-4">세이프존 안내</h3><div className="grid gap-3 md:grid-cols-4">{safezoneOverview.map(([k,v]) => <div key={k} className={cardClass}><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-bold">{v}</p></div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-5">{safezoneSteps.map((s,idx) => <div key={s.stage} className={`${cardClass} border-l-4 border-amber-400`}><p className="text-xs text-slate-500">STEP {idx+1}</p><p className="font-bold mt-1">{s.stage}</p><p className="text-sm mt-1">{s.detail}</p></div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-3">{safezoneFacilities.map((f) => <article key={f.name} className={cardClass}><h4 className="font-bold">{f.name}</h4><p className="text-sm mt-2">{f.detail}</p></article>)}</div></section>; }
function ROAPartnershipSection() { const [selected, setSelected] = useState<string>(roaServices[0]); return <section id="roa" className={sectionClass}><h3 className="text-2xl font-bold mb-4">ROA 제휴 서비스</h3><div className="grid gap-3 md:grid-cols-3">{roaServices.map((s) => <button key={s} onClick={() => setSelected(s)} className={`${cardClass} text-left ${selected === s ? 'ring-2 ring-amber-400' : ''}`}><h4 className="font-semibold">{s}</h4></button>)}</div><div className={`${cardClass} mt-4`}><h4 className="font-bold">{selected}</h4><p className="mt-2 text-sm">{roaServiceDetails[selected]}</p></div></section>; }
function HiringSection({ onOpenHiring }: { onOpenHiring: () => void }) { return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">외인혼혈 세이프존 보조 스태프 3개월 기간제 시범 고용</h3><p className={`${cardClass} text-sm`}>{hiringData.intro}</p><div className="mt-4 grid md:grid-cols-2 gap-3">{hiringData.summary.map(([k,v]) => <div key={k} className={cardClass}><p className="text-xs text-slate-500">{k}</p><p className="font-semibold mt-1">{v}</p></div>)}</div><div className="mt-4 flex justify-end"><button onClick={onOpenHiring} className="rounded-xl bg-brand-navy px-4 py-2 text-white">자세히 보기</button></div></section>; }
function HiringGuidePage({ onGoHome }: { onGoHome: () => void }) { return <section className={sectionClass}><h2 className="text-3xl font-black">기간제 채용 업무 안내</h2><MultiList title="주요 업무" items={hiringData.duties} /><MultiList title="우대 사항" items={hiringData.preferred} /><MultiList title="근무 조건" items={hiringData.conditions} /><MultiList title="지원 절차" items={hiringData.process} /><div className={`${cardClass} mt-4`}><h4 className="font-bold">유의 사항</h4><p className="text-sm mt-2">{hiringData.note}</p></div><button onClick={onGoHome} className="mt-5 rounded bg-brand-navy px-4 py-2 text-white">메인으로 돌아가기</button></section>; }
function MultiList({ title, items }: { title: string; items: string[] }) { return <div className={`${cardClass} mt-4`}><h4 className="font-bold text-lg">{title}</h4><ul className="mt-2 space-y-1 text-sm list-disc pl-5">{items.map((i) => <li key={i}>{i}</li>)}</ul></div>; }
function NoticeSection() { const [selected, setSelected] = useState<string>(notices[0]); return <section className={sectionClass}><h3 className="text-2xl font-bold mb-4">공지사항</h3><div className="grid gap-4 md:grid-cols-2"><div className={cardClass}>{notices.map((n) => <button key={n} onClick={() => setSelected(n)} className={`w-full text-left py-2 border-b last:border-0 ${selected === n ? 'font-bold text-amber-600' : ''}`}>{n}</button>)}</div><div className={cardClass}><h4 className="font-bold">{selected}</h4><p className="mt-2 text-sm">{noticeDetails[selected]}</p></div></div></section>; }
function LoginPage({ signedUser, onLogin }: { signedUser: User | null; onLogin: (id: string) => void }) { const [id, setId] = useState(''); const [pw, setPw] = useState(''); const [err, setErr] = useState(''); return <section className={sectionClass}><div className="max-w-md mx-auto bg-white border rounded-xl p-6"><h2 className="text-2xl font-bold">로그인</h2><input className="w-full border rounded p-2 mt-4" placeholder="아이디" value={id} onChange={(e) => setId(e.target.value)} /><input type="password" className="w-full border rounded p-2 mt-3" placeholder="비밀번호" value={pw} onChange={(e) => setPw(e.target.value)} />{err && <p className="text-red-600 text-sm mt-2">{err}</p>}<button className="w-full mt-4 bg-amber-500 text-white rounded p-2 font-bold" onClick={() => { if (!signedUser) return setErr('먼저 회원가입을 진행해 주세요.'); if (id === signedUser.id && pw === signedUser.password) onLogin(id); else setErr('아이디 또는 비밀번호가 올바르지 않습니다.'); }}>로그인</button></div></section>; }
function SignUpPage({ onSigned }: { onSigned: (user: User) => void }) { const [id, setId] = useState(''); const [pw, setPw] = useState(''); const [confirmPw, setConfirmPw] = useState(''); const [msg, setMsg] = useState(''); return <section className={sectionClass}><div className="max-w-md mx-auto bg-white border rounded-xl p-6"><h2 className="text-2xl font-bold">회원가입</h2><input className="w-full border rounded p-2 mt-4" placeholder="아이디" value={id} onChange={(e) => setId(e.target.value)} /><input type="password" className="w-full border rounded p-2 mt-3" placeholder="비밀번호" value={pw} onChange={(e) => setPw(e.target.value)} /><input type="password" className="w-full border rounded p-2 mt-3" placeholder="비밀번호 확인" value={confirmPw} onChange={(e) => setConfirmPw(e.target.value)} />{msg && <p className="text-sm mt-2 text-red-600">{msg}</p>}<button className="w-full mt-4 bg-brand-navy text-white rounded p-2 font-bold" onClick={() => { if (!id || !pw) return setMsg('아이디와 비밀번호를 입력해 주세요.'); if (pw !== confirmPw) return setMsg('비밀번호 확인이 일치하지 않습니다.'); onSigned({ id, password: pw }); }}>가입하기</button></div></section>; }
function CustomerCenterPage({ onGoHome }: { onGoHome: () => void }) { const [openIdx, setOpenIdx] = useState<number | null>(0); return <section className={sectionClass}><div className={cardClass}><h2 className="text-2xl font-bold">고객센터</h2><p className="mt-3">고객센터 이메일: 365store.ilon@gmail.com</p><h3 className="mt-6 font-bold">FAQ</h3><div className="mt-3 space-y-2">{faqs.map(([q, a], idx) => <div key={q} className="rounded border"><button className="w-full text-left px-3 py-2 font-semibold" onClick={() => setOpenIdx(openIdx === idx ? null : idx)}>{q}</button>{openIdx === idx && <p className="px-3 pb-3 text-sm">{a}</p>}</div>)}</div><button className="mt-4 rounded bg-brand-navy text-white px-4 py-2" onClick={onGoHome}>메인으로 돌아가기</button></div></section>; }
function Footer() { return <footer className="bg-brand-navy text-white mt-8"><div className="mx-auto max-w-7xl px-4 py-8 text-sm"><p>가상 주소: 일온시 중앙순환로 365, 일온세이프타워 1층</p><p className="mt-1">본 사이트의 브랜드·기관·지역은 가상 설정이며 실제와 무관합니다.</p></div></footer>; }
